### PR TITLE
Rename scheduling mod to schedule. Suppress "module inception" lint

### PR DESCRIPTION
**Pull request by cart**
See https://github.com/bevyengine/bevy/pull/7267#discussion_r1087562374 for context

### CODE REVIEW

**Comment by cart** [comment]
Ah wait don't merge this. Left the old files around!

**Comment by cart** [comment]
Fixed!

**Comment by alice-i-cecile** [comment]
I'm fine to defer to your style preferences here. Can you rebase and then do a find-and-replace for this in doc strings too? They won't get caught by the refactoring tool.

**Comment by alice-i-cecile** [comment]
Closing: we can do this in a follow-up PR on bevy main.

**Pull request closed without merging**
